from .departament_getting_service import DepartamentGettingService
from .departament_getting_uuid_service import DepartamentGettingUUIDService
from .departament_creation_service import DepartamentCreationService
